### ISSUE TITLE
Person_ doesn't exist

### ISSUE THREAD

**Issue by Filoz** [pires/simple-jpa-hibernate-guice-desktop-app#1]
Hi,
I am trying the code of this project;
In [PersonDao ](https://github.com/pires/simple-jpa-hibernate-guice-desktop-app/blob/master/src/main/java/com/github/pires/example/dao/PersonDao.java#L22)it refers to Person_.name, is that file missing?

Thankyou!

**Comment by pires** [comment]
That file should be generated to `gen/main/java` and this folder should be used as source folder, as well.. See https://github.com/pires/simple-jpa-hibernate-guice-desktop-app/blob/master/pom.xml#L131
